### ISSUE TITLE
Specify the topics you register in the docker env

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/scenario-manager#48]
Currently, the TMT expects certain schema's to be present in order to send certain messages. But if the expected schemes are not available, it should still start. Preferably, it will listen to the admin tool to get the schemes.

**Comment by erikvullings** [comment]
Can be done using the PRODUCE env setting:

```yaml
  trial_management_tool:
    image: drivereu/trial-management-tool:latest
    depends_on:
      - broker
      - schema_registry
    ports:
      - '3210:3210'
    environment:
      CLIENT_ID: TB-TrialMgmt
      KAFKA_HOST: broker:9092
      SCHEMA_REGISTRY: http://schema_registry:3502
      TRIAL_MANAGER_SERVER_PORT: 3210
      PRODUCE: system_request_change_of_trial_stage,system_tm_phase_message,system_tm_role_player,system_tm_session_mgmt
      SSL: 'false'
      SSL_PFX: certs/TB-TrialMgmt.p12
      SSL_PASSPHRASE: changeit
      SSL_CA: certs/test-ca.pem
    volumes:
      - trial-data:/app/trials
```
